export enum EmailTemplateId {
  CO_PROPOSER_INVITE_ACCEPTED = 'co-proposer-invite-accepted',
  PROPOSAL_SUBMITTED = 'proposal-submitted',
  PROPOSAL_CREATED = 'proposal-created',
  ACCEPTED_PROPOSAL = 'Accepted-Proposal',
  REJECTED_PROPOSAL = 'Rejected-Proposal',
  RESERVED_PROPOSAL = 'Reserved-Proposal',
  REVIEW_REMINDER = 'review-reminder',
  VISIT_REGISTRATION_APPROVED = 'visit-registration-approved',
  VISIT_REGISTRATION_CANCELLED = 'visit-registration-cancelled',
  USER_OFFICE_REGISTRATION_INVITATION_CO_PROPOSER = 'user-office-registration-invitation-co-proposer',
  USER_OFFICE_REGISTRATION_INVITATION_VISIT_REGISTRATION = 'user-office-registration-invitation-visit-registration',
  USER_OFFICE_REGISTRATION_INVITATION_REVIEWER = 'user-office-registration-invitation-reviewer',
  USER_OFFICE_REGISTRATION_INVITATION_USER = 'user-office-registration-invitation-user',
  INTERNAL_REVIEW_CREATED = 'internal-review-created',
  INTERNAL_REVIEW_UPDATED = 'internal-review-updated',
  INTERNAL_REVIEW_DELETED = 'internal-review-deleted',
  CALL_CREATED_EMAIL = 'call-created-email',
  FEEDBACK_REQUEST = 'feedback-request',
}
