# Specify a different separator for branch names

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '08:00'
    # Only 1 PR at a time so e2e tests pass and automerge completes before the next PR opens
    open-pull-requests-limit: 1
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen because docker hub doesn't want slashes
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: '-'
    versioning-strategy: increase-if-necessary
    cooldown:
      default-days: 7

  - package-ecosystem: 'npm'
    directory: '/apps/backend'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '10:00'
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: '-'
    versioning-strategy: increase-if-necessary
    cooldown:
      default-days: 7

  - package-ecosystem: 'npm'
    directory: '/apps/frontend'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '12:00'
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: '-'
    versioning-strategy: increase-if-necessary
    cooldown:
      default-days: 7

  - package-ecosystem: 'npm'
    directory: '/apps/e2e'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '08:00'
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: '-'
    versioning-strategy: increase-if-necessary
    cooldown:
      default-days: 7

  - package-ecosystem: 'npm'
    directory: '/validation'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '10:00'
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: '-'
    versioning-strategy: increase-if-necessary
    cooldown:
      default-days: 7

  - package-ecosystem: 'docker'
    directories:
      - '/apps/backend'
      - '/apps/frontend'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '10:00'
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: '-'
    allow:
      - update-types:
          - 'version-update:semver-minor'
          - 'version-update:semver-patch'
    cooldown:
      default-days: 7
