ARG WINDOWS_VERSION
FROM docker-registry.devs.facilities.rl.ac.uk/bisapps-node:12-servercore${WINDOWS_VERSION}-1.0.0-SNAPSHOT

# Create app directory
WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY . .

RUN mkdir downloads

RUN npm run tsc

EXPOSE 4000
CMD [ "node", "./build/index.js" ]
