// This file contains unique tokens for each dependency
export const Tokens = {
  AdminDataSource: Symbol('AdminDataSource'),
  AssetRegistrar: Symbol('AssetRegistrar'),
  CallDataSource: Symbol('CallDataSource'),
  ConfigureEnvironment: Symbol('ConfigureEnvironment'),
  ConfigureLogger: Symbol('ConfigureLogger'),
  CoProposerClaimDataSource: Symbol('CoProposerClaimDataSource'),
  EmailEventHandler: Symbol('EmailEventHandler'),
  EventBus: Symbol('EventBus'),
  EventLogsDataSource: Symbol('EventLogsDataSource'),
  FeedbackDataSource: Symbol('FeedbackDataSource'),
  FileDataSource: Symbol('FileDataSource'),
  GenericTemplateDataSource: Symbol('GenericTemplateDataSource'),
  InstrumentDataSource: Symbol('InstrumentDataSource'),
  InviteDataSource: Symbol('InviteDataSource'),
  CoProposerInviteAuthorization: Symbol('CoProposerInviteAuthorization'),
  TechniqueDataSource: Symbol('TechniqueDataSource'),
  ListenToMessageQueue: Symbol('ListenToMessageQueue'),
  MailService: Symbol('MailService'),
  PdfTemplateDataSource: Symbol('PdfTemplateDataSource'),
  PostToMessageQueue: Symbol('PostToMessageQueue'),
  ProposalDataSource: Symbol('ProposalDataSource'),
  ProposalEsiDataSource: Symbol('ProposalEsiDataSource'),
  ProposalSettingsDataSource: Symbol('ProposalSettingsDataSource'),
  StatusActionsDataSource: Symbol('StatusActionsDataSource'),
  QuestionaryDataSource: Symbol('QuestionaryDataSource'),
  RedeemCodesDataSource: Symbol('RedeemCodesDataSource'),
  RoleClaimDataSource: Symbol('RoleClaimDataSource'),
  ReviewDataSource: Symbol('ReviewDataSource'),
  FapDataSource: Symbol('FapDataSource'),
  SampleDataSource: Symbol('SampleDataSource'),
  SampleEsiDataSource: Symbol('SampleEsiDataSource'),
  ScheduledEventDataSource: Symbol('ScheduledEventDataSource'),
  ShipmentDataSource: Symbol('ShipmentDataSource'),
  SystemDataSource: Symbol('SystemDataSource'),
  TemplateDataSource: Symbol('TemplateDataSource'),
  UnitDataSource: Symbol('UnitDataSource'),
  UserAuthorization: Symbol('UserAuthorization'),
  ProposalAuthorization: Symbol('ProposalAuthorization'),
  UserDataSource: Symbol('UserDataSource'),
  VisitDataSource: Symbol('VisitDataSource'),
  PredefinedMessageDataSource: Symbol('PredefinedMessageDataSource'),
  InternalReviewDataSource: Symbol('InternalReviewDataSource'),
  FapDataColumns: Symbol('FapDataColumns'),
  FapDataRow: Symbol('FapDataRow'),
  PopulateRow: Symbol('PopulateRow'),
  PopulateCallRow: Symbol('PopulateCallRow'),
  DownloadService: Symbol('DownloadService'),
  StatusActionsLogsDataSource: Symbol('StatusActionsLogsDataSource'),
  ProposalInternalCommentsDataSource: Symbol(
    'ProposalInternalCommentsDataSource'
  ),
  BasicUserDetailsLoader: Symbol('BasicUserDetailsLoader'),
};
