// This file contains unique tokens for each dependency
export const Tokens = {
  AdminDataSource: Symbol('AdminDataSource'),
  AssetRegistrar: Symbol('AssetRegistrar'),
  CallDataSource: Symbol('CallDataSource'),
  ConfigureEnvironment: Symbol('ConfigureEnvironment'),
  ConfigureLogger: Symbol('ConfigureLogger'),
  CoProposerClaimDataSource: Symbol('CoProposerClaimDataSource'),
  DataAccessUsersDataSource: Symbol('DataAccessUsersDataSource'),
  DataAccessUsersAuthorization: Symbol('DataAccessUsersAuthorization'),
  EmailEventHandler: Symbol('EmailEventHandler'),
  EventBus: Symbol('EventBus'),
  EventLogsDataSource: Symbol('EventLogsDataSource'),
  FeedbackDataSource: Symbol('FeedbackDataSource'),
  FileDataSource: Symbol('FileDataSource'),
  GenericTemplateDataSource: Symbol('GenericTemplateDataSource'),
  InstrumentDataSource: Symbol('InstrumentDataSource'),
  InviteDataSource: Symbol('InviteDataSource'),
  TechniqueDataSource: Symbol('TechniqueDataSource'),
  ListenToMessageQueue: Symbol('ListenToMessageQueue'),
  LoggingHandler: Symbol('LoggingHandler'),
  MailService: Symbol('MailService'),
  ProposalPdfTemplateDataSource: Symbol('ProposalPdfTemplateDataSource'),
  ExperimentSafetyPdfTemplateDataSource: Symbol(
    'ExperimentSafetyPdfTemplateDataSource'
  ),
  PostToMessageQueue: Symbol('PostToMessageQueue'),
  ProposalDataSource: Symbol('ProposalDataSource'),
  ProposalEsiDataSource: Symbol('ProposalEsiDataSource'),
  ProposalSettingsDataSource: Symbol('ProposalSettingsDataSource'),
  StatusActionsDataSource: Symbol('StatusActionsDataSource'),
  QuestionaryDataSource: Symbol('QuestionaryDataSource'),
  RoleClaimDataSource: Symbol('RoleClaimDataSource'),
  ReviewDataSource: Symbol('ReviewDataSource'),
  FapDataSource: Symbol('FapDataSource'),
  SampleDataSource: Symbol('SampleDataSource'),
  SampleEsiDataSource: Symbol('SampleEsiDataSource'),
  ShipmentDataSource: Symbol('ShipmentDataSource'),
  SystemDataSource: Symbol('SystemDataSource'),
  TemplateDataSource: Symbol('TemplateDataSource'),
  UnitDataSource: Symbol('UnitDataSource'),
  UserAuthorization: Symbol('UserAuthorization'),
  ProposalAuthorization: Symbol('ProposalAuthorization'),
  VisitAuthorization: Symbol('VisitAuthorization'),
  VisitRegistrationAuthorization: Symbol('VisitRegistrationAuthorization'),
  UserDataSource: Symbol('UserDataSource'),
  VisitDataSource: Symbol('VisitDataSource'),
  VisitRegistrationClaimDataSource: Symbol('VisitRegistrationClaimDataSource'),
  PredefinedMessageDataSource: Symbol('PredefinedMessageDataSource'),
  InternalReviewDataSource: Symbol('InternalReviewDataSource'),
  FapDataColumns: Symbol('FapDataColumns'),
  FapDataRow: Symbol('FapDataRow'),
  PopulateRow: Symbol('PopulateRow'),
  PopulateCallRow: Symbol('PopulateCallRow'),
  StatusActionsLogsDataSource: Symbol('StatusActionsLogsDataSource'),
  ProposalInternalCommentsDataSource: Symbol(
    'ProposalInternalCommentsDataSource'
  ),
  WorkflowDataSource: Symbol('WorkflowDataSource'),
  StatusDataSource: Symbol('StatusDataSource'),
  ExperimentDataSource: Symbol('ExperimentDataSource'),
  BasicUserDetailsLoader: Symbol('BasicUserDetailsLoader'),
  TagDataSource: Symbol('TagDataSource'),
  RoleDataSource: Symbol('RoleDataSource'),
};
