query getUserProposals(
  $first: Int, 
  $offset: Int
) {
  me {
    paginatedProposals(
      first: $first, 
      offset: $offset
    ) {
      totalCount
      userProposals {
        primaryKey
        proposalId
        title
        status {
          ...status
        }
        publicStatus
        statusId
        created
        finalStatus
        notified
        submitted
        proposer {
          id
        }
        call {
          id
          shortCode
          isActive
          isActiveInternal
          referenceNumberFormat
          startCall
          endCall
          endCallInternal
        }
      }
    }
  }
}
