// This file contains unique tokens for each dependency
export const Tokens = {
  AdminDataSource: Symbol('AdminDataSource'),
  AssetRegistrar: Symbol('AssetRegistrar'),
  CallDataSource: Symbol('CallDataSource'),
  ConfigureEnvironment: Symbol('ConfigureEnvironment'),
  ConfigureLogger: Symbol('ConfigureLogger'),
  EmailEventHandler: Symbol('EmailEventHandler'),
  EventLogsDataSource: Symbol('EventLogsDataSource'),
  FeedbackDataSource: Symbol('FeedbackDataSource'),
  FileDataSource: Symbol('FileDataSource'),
  GenericTemplateDataSource: Symbol('GenericTemplateDataSource'),
  InstrumentDataSource: Symbol('InstrumentDataSource'),
  ListenToMessageQueue: Symbol('ListenToMessageQueue'),
  MailService: Symbol('MailService'),
  PostToMessageQueue: Symbol('PostToMessageQueue'),
  ProposalDataSource: Symbol('ProposalDataSource'),
  ProposalEsiDataSource: Symbol('ProposalEsiDataSource'),
  ProposalSettingsDataSource: Symbol('ProposalSettingsDataSource'),
  QuestionaryDataSource: Symbol('QuestionaryDataSource'),
  ReviewDataSource: Symbol('ReviewDataSource'),
  SEPDataSource: Symbol('SEPDataSource'),
  SampleDataSource: Symbol('SampleDataSource'),
  SampleEsiDataSource: Symbol('SampleEsiDataSource'),
  ScheduledEventDataSource: Symbol('ScheduledEventDataSource'),
  ShipmentDataSource: Symbol('ShipmentDataSource'),
  SystemDataSource: Symbol('SystemDataSource'),
  TemplateDataSource: Symbol('TemplateDataSource'),
  UnitDataSource: Symbol('UnitDataSource'),
  UserAuthorization: Symbol('UserAuthorization'),
  UserDataSource: Symbol('UserDataSource'),
  VisitDataSource: Symbol('VisitDataSource'),
};
