// This file contains unique tokens for each dependency
export const Tokens = {
  AdminDataSource: Symbol('AdminDataSource'),
  CallDataSource: Symbol('CallDataSource'),
  EventLogsDataSource: Symbol('EventLogsDataSource'),
  FileDataSource: Symbol('FileDataSource'),
  InstrumentDataSource: Symbol('InstrumentDataSource'),
  ProposalDataSource: Symbol('ProposalDataSource'),
  ProposalSettingsDataSource: Symbol('ProposalSettingsDataSource'),
  QuestionaryAuthorization: Symbol('QuestionaryAuthorization'),
  QuestionaryDataSource: Symbol('QuestionaryDataSource'),
  ReviewDataSource: Symbol('ReviewDataSource'),
  SEPDataSource: Symbol('SEPDataSource'),
  SampleAuthorization: Symbol('SampleAuthorization'),
  GenericTemplateAuthorization: Symbol('GenericTemplateAuthorization'),
  SampleDataSource: Symbol('SampleDataSource'),
  GenericTemplateDataSource: Symbol('GenericTemplateDataSource'),
  ShipmentAuthorization: Symbol('ShipmentAuthorization'),
  ShipmentDataSource: Symbol('ShipmentDataSource'),
  SystemDataSource: Symbol('SystemDataSource'),
  TemplateDataSource: Symbol('TemplateDataSource'),
  UserAuthorization: Symbol('UserAuthorization'),
  UserDataSource: Symbol('UserDataSource'),
  AssetRegistrar: Symbol('AssetRegistrar'),
  PostToMessageQueue: Symbol('PostToMessageQueue'),
  ListenToMessageQueue: Symbol('ListenToMessageQueue'),
  MailService: Symbol('MailService'),
  VisitDataSource: Symbol('VisitDataSource'),
  VisitAuthorization: Symbol('VisitAuthorization'),
  ProposalEsiDataSource: Symbol('ProposalEsiDataSource'),
  SampleEsiDataSource: Symbol('SampleEsiDataSource'),
  ConfigureEnvironment: Symbol('ConfigureEnvironment'),
};
