export const StfcFapDataColumns = [
  'Proposal Reference Number',
  'Principal Investigator',
  'PI Country',
  'Instrument Name',
  'Requested Time',
  'Proposal Title',
  'Technical Review Comment',
  'Average score',
  'Reviewer 1',
  'Reviewer 1 score',
  'Reviewer 1 review comment',
  'Reviewer 2',
  'Reviewer 2 score',
  'Reviewer 2 review comment',
  'Reviewer 3',
  'Reviewer 3 score',
  'Reviewer 3 review comment',
];
