DO
$$
BEGIN
	IF register_patch('AddNationalitiesTable.sql', 'fredrikbolmsten', 'Adding new table for nationalities', '2019-11-19') THEN
	BEGIN


        CREATE TABLE IF NOT EXISTS nationalities(
            nationality_id serial UNIQUE,
            nationality varchar(50) DEFAULT NULL
        );


        INSERT INTO nationalities (nationality) values ('Afghan');
        INSERT INTO nationalities (nationality) values ('Albanian');
        INSERT INTO nationalities (nationality) values ('Algerian');
        INSERT INTO nationalities (nationality) values ('American');
        INSERT INTO nationalities (nationality) values ('Andorran');
        INSERT INTO nationalities (nationality) values ('Angolan');
        INSERT INTO nationalities (nationality) values ('Antiguans');
        INSERT INTO nationalities (nationality) values ('Argentinean');
        INSERT INTO nationalities (nationality) values ('Armenian');
        INSERT INTO nationalities (nationality) values ('Australian');
        INSERT INTO nationalities (nationality) values ('Austrian');
        INSERT INTO nationalities (nationality) values ('Azerbaijani');
        INSERT INTO nationalities (nationality) values ('Bahamian');
        INSERT INTO nationalities (nationality) values ('Bahraini');
        INSERT INTO nationalities (nationality) values ('Bangladeshi');
        INSERT INTO nationalities (nationality) values ('Barbadian');
        INSERT INTO nationalities (nationality) values ('Barbudans');
        INSERT INTO nationalities (nationality) values ('Batswana');
        INSERT INTO nationalities (nationality) values ('Belarusian');
        INSERT INTO nationalities (nationality) values ('Belgian');
        INSERT INTO nationalities (nationality) values ('Belizean');
        INSERT INTO nationalities (nationality) values ('Beninese');
        INSERT INTO nationalities (nationality) values ('Bhutanese');
        INSERT INTO nationalities (nationality) values ('Bolivian');
        INSERT INTO nationalities (nationality) values ('Bosnian');
        INSERT INTO nationalities (nationality) values ('Brazilian');
        INSERT INTO nationalities (nationality) values ('British');
        INSERT INTO nationalities (nationality) values ('Bruneian');
        INSERT INTO nationalities (nationality) values ('Bulgarian');
        INSERT INTO nationalities (nationality) values ('Burkinabe');
        INSERT INTO nationalities (nationality) values ('Burmese');
        INSERT INTO nationalities (nationality) values ('Burundian');
        INSERT INTO nationalities (nationality) values ('Cambodian');
        INSERT INTO nationalities (nationality) values ('Cameroonian');
        INSERT INTO nationalities (nationality) values ('Canadian');
        INSERT INTO nationalities (nationality) values ('Cape Verdean');
        INSERT INTO nationalities (nationality) values ('Central African');
        INSERT INTO nationalities (nationality) values ('Chadian');
        INSERT INTO nationalities (nationality) values ('Chilean');
        INSERT INTO nationalities (nationality) values ('Chinese');
        INSERT INTO nationalities (nationality) values ('Colombian');
        INSERT INTO nationalities (nationality) values ('Comoran');
        INSERT INTO nationalities (nationality) values ('Congolese');
        INSERT INTO nationalities (nationality) values ('Costa Rican');
        INSERT INTO nationalities (nationality) values ('Croatian');
        INSERT INTO nationalities (nationality) values ('Cuban');
        INSERT INTO nationalities (nationality) values ('Cypriot');
        INSERT INTO nationalities (nationality) values ('Czech');
        INSERT INTO nationalities (nationality) values ('Danish');
        INSERT INTO nationalities (nationality) values ('Djibouti');
        INSERT INTO nationalities (nationality) values ('Dominican');
        INSERT INTO nationalities (nationality) values ('Dutch');
        INSERT INTO nationalities (nationality) values ('East Timorese');
        INSERT INTO nationalities (nationality) values ('Ecuadorean');
        INSERT INTO nationalities (nationality) values ('Egyptian');
        INSERT INTO nationalities (nationality) values ('Emirian');
        INSERT INTO nationalities (nationality) values ('Equatorial Guinean');
        INSERT INTO nationalities (nationality) values ('Eritrean');
        INSERT INTO nationalities (nationality) values ('Estonian');
        INSERT INTO nationalities (nationality) values ('Ethiopian');
        INSERT INTO nationalities (nationality) values ('Fijian');
        INSERT INTO nationalities (nationality) values ('Filipino');
        INSERT INTO nationalities (nationality) values ('Finnish');
        INSERT INTO nationalities (nationality) values ('French');
        INSERT INTO nationalities (nationality) values ('Gabonese');
        INSERT INTO nationalities (nationality) values ('Gambian');
        INSERT INTO nationalities (nationality) values ('Georgian');
        INSERT INTO nationalities (nationality) values ('German');
        INSERT INTO nationalities (nationality) values ('Ghanaian');
        INSERT INTO nationalities (nationality) values ('Greek');
        INSERT INTO nationalities (nationality) values ('Grenadian');
        INSERT INTO nationalities (nationality) values ('Guatemalan');
        INSERT INTO nationalities (nationality) values ('Guinea-Bissauan');
        INSERT INTO nationalities (nationality) values ('Guinean');
        INSERT INTO nationalities (nationality) values ('Guyanese');
        INSERT INTO nationalities (nationality) values ('Haitian');
        INSERT INTO nationalities (nationality) values ('Herzegovinian');
        INSERT INTO nationalities (nationality) values ('Honduran');
        INSERT INTO nationalities (nationality) values ('Hungarian');
        INSERT INTO nationalities (nationality) values ('Icelander');
        INSERT INTO nationalities (nationality) values ('Indian');
        INSERT INTO nationalities (nationality) values ('Indonesian');
        INSERT INTO nationalities (nationality) values ('Iranian');
        INSERT INTO nationalities (nationality) values ('Iraqi');
        INSERT INTO nationalities (nationality) values ('Irish');
        INSERT INTO nationalities (nationality) values ('Israeli');
        INSERT INTO nationalities (nationality) values ('Italian');
        INSERT INTO nationalities (nationality) values ('Ivorian');
        INSERT INTO nationalities (nationality) values ('Jamaican');
        INSERT INTO nationalities (nationality) values ('Japanese');
        INSERT INTO nationalities (nationality) values ('Jordanian');
        INSERT INTO nationalities (nationality) values ('Kazakhstani');
        INSERT INTO nationalities (nationality) values ('Kenyan');
        INSERT INTO nationalities (nationality) values ('Kittian and Nevisian');
        INSERT INTO nationalities (nationality) values ('Kuwaiti');
        INSERT INTO nationalities (nationality) values ('Kyrgyz');
        INSERT INTO nationalities (nationality) values ('Laotian');
        INSERT INTO nationalities (nationality) values ('Latvian');
        INSERT INTO nationalities (nationality) values ('Lebanese');
        INSERT INTO nationalities (nationality) values ('Liberian');
        INSERT INTO nationalities (nationality) values ('Libyan');
        INSERT INTO nationalities (nationality) values ('Liechtensteiner');
        INSERT INTO nationalities (nationality) values ('Lithuanian');
        INSERT INTO nationalities (nationality) values ('Luxembourger');
        INSERT INTO nationalities (nationality) values ('Macedonian');
        INSERT INTO nationalities (nationality) values ('Malagasy');
        INSERT INTO nationalities (nationality) values ('Malawian');
        INSERT INTO nationalities (nationality) values ('Malaysian');
        INSERT INTO nationalities (nationality) values ('Maldivan');
        INSERT INTO nationalities (nationality) values ('Malian');
        INSERT INTO nationalities (nationality) values ('Maltese');
        INSERT INTO nationalities (nationality) values ('Marshallese');
        INSERT INTO nationalities (nationality) values ('Mauritanian');
        INSERT INTO nationalities (nationality) values ('Mauritian');
        INSERT INTO nationalities (nationality) values ('Mexican');
        INSERT INTO nationalities (nationality) values ('Micronesian');
        INSERT INTO nationalities (nationality) values ('Moldovan');
        INSERT INTO nationalities (nationality) values ('Monacan');
        INSERT INTO nationalities (nationality) values ('Mongolian');
        INSERT INTO nationalities (nationality) values ('Moroccan');
        INSERT INTO nationalities (nationality) values ('Mosotho');
        INSERT INTO nationalities (nationality) values ('Motswana');
        INSERT INTO nationalities (nationality) values ('Mozambican');
        INSERT INTO nationalities (nationality) values ('Namibian');
        INSERT INTO nationalities (nationality) values ('Nauruan');
        INSERT INTO nationalities (nationality) values ('Nepalese');
        INSERT INTO nationalities (nationality) values ('New Zealander');
        INSERT INTO nationalities (nationality) values ('Ni-Vanuatu');
        INSERT INTO nationalities (nationality) values ('Nicaraguan');
        INSERT INTO nationalities (nationality) values ('Nigerien');
        INSERT INTO nationalities (nationality) values ('North Korean');
        INSERT INTO nationalities (nationality) values ('Northern Irish');
        INSERT INTO nationalities (nationality) values ('Norwegian');
        INSERT INTO nationalities (nationality) values ('Omani');
        INSERT INTO nationalities (nationality) values ('Pakistani');
        INSERT INTO nationalities (nationality) values ('Palauan');
        INSERT INTO nationalities (nationality) values ('Panamanian');
        INSERT INTO nationalities (nationality) values ('Papua New Guinean');
        INSERT INTO nationalities (nationality) values ('Paraguayan');
        INSERT INTO nationalities (nationality) values ('Peruvian');
        INSERT INTO nationalities (nationality) values ('Polish');
        INSERT INTO nationalities (nationality) values ('Portuguese');
        INSERT INTO nationalities (nationality) values ('Qatari');
        INSERT INTO nationalities (nationality) values ('Romanian');
        INSERT INTO nationalities (nationality) values ('Russian');
        INSERT INTO nationalities (nationality) values ('Rwandan');
        INSERT INTO nationalities (nationality) values ('Saint Lucian');
        INSERT INTO nationalities (nationality) values ('Salvadoran');
        INSERT INTO nationalities (nationality) values ('Samoan');
        INSERT INTO nationalities (nationality) values ('San Marinese');
        INSERT INTO nationalities (nationality) values ('Sao Tomean');
        INSERT INTO nationalities (nationality) values ('Saudi');
        INSERT INTO nationalities (nationality) values ('Senegalese');
        INSERT INTO nationalities (nationality) values ('Serbian');
        INSERT INTO nationalities (nationality) values ('Seychellois');
        INSERT INTO nationalities (nationality) values ('Sierra Leonean');
        INSERT INTO nationalities (nationality) values ('Singaporean');
        INSERT INTO nationalities (nationality) values ('Slovakian');
        INSERT INTO nationalities (nationality) values ('Slovenian');
        INSERT INTO nationalities (nationality) values ('Solomon Islander');
        INSERT INTO nationalities (nationality) values ('Somali');
        INSERT INTO nationalities (nationality) values ('South African');
        INSERT INTO nationalities (nationality) values ('South Korean');
        INSERT INTO nationalities (nationality) values ('Spanish');
        INSERT INTO nationalities (nationality) values ('Sri Lankan');
        INSERT INTO nationalities (nationality) values ('Sudanese');
        INSERT INTO nationalities (nationality) values ('Surinamer');
        INSERT INTO nationalities (nationality) values ('Swazi');
        INSERT INTO nationalities (nationality) values ('Swedish');
        INSERT INTO nationalities (nationality) values ('Swiss');
        INSERT INTO nationalities (nationality) values ('Syrian');
        INSERT INTO nationalities (nationality) values ('Taiwanese');
        INSERT INTO nationalities (nationality) values ('Tajik');
        INSERT INTO nationalities (nationality) values ('Tanzanian');
        INSERT INTO nationalities (nationality) values ('Thai');
        INSERT INTO nationalities (nationality) values ('Togolese');
        INSERT INTO nationalities (nationality) values ('Tongan');
        INSERT INTO nationalities (nationality) values ('Trinidadian or Tobagonian');
        INSERT INTO nationalities (nationality) values ('Tunisian');
        INSERT INTO nationalities (nationality) values ('Turkish');
        INSERT INTO nationalities (nationality) values ('Tuvaluan');
        INSERT INTO nationalities (nationality) values ('Ugandan');
        INSERT INTO nationalities (nationality) values ('Ukrainian');
        INSERT INTO nationalities (nationality) values ('Uruguayan');
        INSERT INTO nationalities (nationality) values ('Uzbekistani');
        INSERT INTO nationalities (nationality) values ('Venezuelan');
        INSERT INTO nationalities (nationality) values ('Vietnamese');
        INSERT INTO nationalities (nationality) values ('Yemenite');
        INSERT INTO nationalities (nationality) values ('Zambian');
        INSERT INTO nationalities (nationality) values ('Zimbabwean');



    END;
	END IF;
END;
$$
LANGUAGE plpgsql;
