DO
$$
BEGIN
	IF register_patch('AddInstitutionTable.sql', 'fredrikbolmsten', 'Adding new table for institution', '2019-11-19') THEN
	BEGIN
  

        CREATE TABLE IF NOT EXISTS institutions(
            institution_id serial UNIQUE,
            institution varchar(100) DEFAULT NULL,
            verified boolean DEFAULT TRUE
        );

        INSERT INTO institutions (institution) values ('Other');
        INSERT INTO institutions (institution) values ('A.A Baikov Institute of Metallurgy and Materials Science');
        INSERT INTO institutions (institution) values ('ALBA Synchrotron Light Source');
        INSERT INTO institutions (institution) values ('AGH University of Science and Technology');
        INSERT INTO institutions (institution) values ('Aarhus University');
        INSERT INTO institutions (institution) values ('Aberystwyth University');
        INSERT INTO institutions (institution) values ('Adam Mickiewicz University');
        INSERT INTO institutions (institution) values ('Agricultural University of Athens');
        INSERT INTO institutions (institution) values ('Aix-Marseille Université');
        INSERT INTO institutions (institution) values ('Aristotle University of Thessaloniki');
        INSERT INTO institutions (institution) values ('Arizona State University');
        INSERT INTO institutions (institution) values ('Akdeniz University');
        INSERT INTO institutions (institution) values ('Australian Synchrotron');
        INSERT INTO institutions (institution) values ('Atomic Energy Authority of Egypt, Nuclear Research Center');
        INSERT INTO institutions (institution) values ('BAM Federal Institute for Materials Research and Testing');
        INSERT INTO institutions (institution) values ('Beijing University of Technology');
        INSERT INTO institutions (institution) values ('Bergische Universität Wuppertal');
        INSERT INTO institutions (institution) values ('Bielefeld University');
        INSERT INTO institutions (institution) values ('Ben-Gurion University');
        INSERT INTO institutions (institution) values ('Blekinge Institute of Technology');
        INSERT INTO institutions (institution) values ('Boreskov Institute of Catalysis');
        INSERT INTO institutions (institution) values ('Boston University');
        INSERT INTO institutions (institution) values ('Brazilian Synchrotron Light Laboratory (LNLS)');
        INSERT INTO institutions (institution) values ('Brno University of Technology');
        INSERT INTO institutions (institution) values ('Brock University');
        INSERT INTO institutions (institution) values ('Brookhaven National Labs');
        INSERT INTO institutions (institution) values ('CSIC - Instituto de Ciencia de Materiales de Madrid (ICMM)');
        INSERT INTO institutions (institution) values ('CSIC - Instituto de Estructura de la Materia (IEM)');
        INSERT INTO institutions (institution) values ('CEA - Commissariat à l’énergie atomique');
        INSERT INTO institutions (institution) values ('Carnegie Mellon University');
        INSERT INTO institutions (institution) values ('Center for High Pressure Science & Technology Advanced Research (HPSTAR)');
        INSERT INTO institutions (institution) values ('Center for Physical Sciences and Technology');
        INSERT INTO institutions (institution) values ('CSIC - Instituto de Química Física Rocasolano');
        INSERT INTO institutions (institution) values ('Canadian Light Source Inc.');
        INSERT INTO institutions (institution) values ('Carlsberg Laboratory');
        INSERT INTO institutions (institution) values ('Cardiff University');
        INSERT INTO institutions (institution) values ('Center of Research and Advances Studies of the National Polytechnic Institute, (CINVESTAV-IPN)');
        INSERT INTO institutions (institution) values ('Centre for Art Technological Studies and Conservation (CATS)');
        INSERT INTO institutions (institution) values ('Central Research Institute of Electric Power Industry (CRIEPI)');
        INSERT INTO institutions (institution) values ('Chalmers University of Technology (CTH)');
        INSERT INTO institutions (institution) values ('Centro Universitario de la Defensa');
        INSERT INTO institutions (institution) values ('Centro Atomico Bariloche (CNEA)');
        INSERT INTO institutions (institution) values ('Charles University in Prague');
        INSERT INTO institutions (institution) values ('Chiba University');
        INSERT INTO institutions (institution) values ('Chinese Academy of Sciences');
        INSERT INTO institutions (institution) values ('CiC nanoGUNE Consolider');
        INSERT INTO institutions (institution) values ('Copenhagen University Hospital Hvidovre');
        INSERT INTO institutions (institution) values ('Cornell University');
        INSERT INTO institutions (institution) values ('Cukurova University');
        INSERT INTO institutions (institution) values ('Consejo Superior de Investigaciones Cientificas');
        INSERT INTO institutions (institution) values ('Daresbury Laboratory');
        INSERT INTO institutions (institution) values ('Delft University of Technology');
        INSERT INTO institutions (institution) values ('Democritus University of Thrace');
        INSERT INTO institutions (institution) values ('Deutsches Elektronen-Synchrotron DESY');
        INSERT INTO institutions (institution) values ('Diamond Light Source');
        INSERT INTO institutions (institution) values ('Drexel University');
        INSERT INTO institutions (institution) values ('Donostia International Physics Center (DIPC)');
        INSERT INTO institutions (institution) values ('Dublin City University');
        INSERT INTO institutions (institution) values ('Durham University');
        INSERT INTO institutions (institution) values ('Duke University');
        INSERT INTO institutions (institution) values ('Dongguk University');
        INSERT INTO institutions (institution) values ('EMBL Hamburg');
        INSERT INTO institutions (institution) values ('European Synchrotron Radiation Facility (ESRF)');
        INSERT INTO institutions (institution) values ('ETH Zürich');
        INSERT INTO institutions (institution) values ('ELI Beamlines');
        INSERT INTO institutions (institution) values ('EMBL Grenoble');
        INSERT INTO institutions (institution) values ('ESPCI ParisTech');
        INSERT INTO institutions (institution) values ('Swiss Federal Institute of Aquatic Science and Technology');
        INSERT INTO institutions (institution) values ('Eberhard Karls Universität Tübingen');
        INSERT INTO institutions (institution) values ('Ecole Polytechnique Federale de Lausanne');
        INSERT INTO institutions (institution) values ('Eindhoven University of Technology');
        INSERT INTO institutions (institution) values ('Elettra-Sincrotrone Trieste');
        INSERT INTO institutions (institution) values ('Eli-alps Research Institute');
        INSERT INTO institutions (institution) values ('Escuela Superior de Ingenieria Quimica e Industrias Extractivas (ESIQIE-IPN)');
        INSERT INTO institutions (institution) values ('European Institute for Energy Research (EIFER)');
        INSERT INTO institutions (institution) values ('European Organisation for Nuclear Research (CERN)');
        INSERT INTO institutions (institution) values ('European XFEL GmbH');
        INSERT INTO institutions (institution) values ('European Spallation Source ERIC (ESS)');
        INSERT INTO institutions (institution) values ('Federal University of Rio Grande do Sul');
        INSERT INTO institutions (institution) values ('Forschungszentrum Jülich');
        INSERT INTO institutions (institution) values ('Firc Institute of Molecular Oncology Foundation, European Institute of Oncology - IFOM-IEO');
        INSERT INTO institutions (institution) values ('Freie Universität Berlin');
        INSERT INTO institutions (institution) values ('Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU)');
        INSERT INTO institutions (institution) values ('Fritz-Haber-Institut der Max-Planck-Gesellschaft');
        INSERT INTO institutions (institution) values ('Friedrich Schiller University Jena');
        INSERT INTO institutions (institution) values ('Fudan University');
        INSERT INTO institutions (institution) values ('GKSS Research Centre Geesthacht');
        INSERT INTO institutions (institution) values ('Fujian Institute of Research on the Structure of Matter');
        INSERT INTO institutions (institution) values ('GW Krieger School');
        INSERT INTO institutions (institution) values ('Gdansk University of Technology');
        INSERT INTO institutions (institution) values ('Geologic Survey of Denmark and Greenland (GEUS)');
        INSERT INTO institutions (institution) values ('Geological Survey of Norway (NGU)');
        INSERT INTO institutions (institution) values ('Georg-August-Universität Göttingen');
        INSERT INTO institutions (institution) values ('Georgia Institute of Technology');
        INSERT INTO institutions (institution) values ('Ghent University');
        INSERT INTO institutions (institution) values ('George Washington University');
        INSERT INTO institutions (institution) values ('Goethe Universität Frankfurt');
        INSERT INTO institutions (institution) values ('Hagedorn Institute');
        INSERT INTO institutions (institution) values ('Halmstad University');
        INSERT INTO institutions (institution) values ('Hannover Medical School (MHH)');
        INSERT INTO institutions (institution) values ('HIST, Sør-Trøndelag University College');
        INSERT INTO institutions (institution) values ('Gwangju Institute of Science and Technology');
        INSERT INTO institutions (institution) values ('Helmholtz Centre for Infection Research');
        INSERT INTO institutions (institution) values ('Helmholtz-Zentrum Berlin');
        INSERT INTO institutions (institution) values ('Hellenic Pasteur Institute');
        INSERT INTO institutions (institution) values ('Helmholtz-Zentrum Geesthacht');
        INSERT INTO institutions (institution) values ('Hindustan University');
        INSERT INTO institutions (institution) values ('Hiroshima University');
        INSERT INTO institutions (institution) values ('Humboldt Universität zu Berlin');
        INSERT INTO institutions (institution) values ('ICMAB-CSIC');
        INSERT INTO institutions (institution) values ('IMARES, Institute for Marine Resources and Ecosystem Studies');
        INSERT INTO institutions (institution) values ('IRCCS Ospedale San Raffaele');
        INSERT INTO institutions (institution) values ('Hokkaido University');
        INSERT INTO institutions (institution) values ('IRCER - Institut de Recherche sur les Céramiques');
        INSERT INTO institutions (institution) values ('IRELEC-ALCEN');
        INSERT INTO institutions (institution) values ('ITMO University');
        INSERT INTO institutions (institution) values ('ISSP RAS');
        INSERT INTO institutions (institution) values ('Indian Institute of Science (IISc)');
        INSERT INTO institutions (institution) values ('Indian Association for the Cultivation of Science');
        INSERT INTO institutions (institution) values ('Imperial College London');
        INSERT INTO institutions (institution) values ('Immanuel Kant Baltic Federal University (IK BFU)');
        INSERT INTO institutions (institution) values ('Indian Institute of Technology (BHU)');
        INSERT INTO institutions (institution) values ('Indian Institute of Technology Bombay');
        INSERT INTO institutions (institution) values ('Insituto de Tecnologia Quimica e Biologia (ITQB)');
        INSERT INTO institutions (institution) values ('Institut Laue-Langevin (ILL)');
        INSERT INTO institutions (institution) values ('Institut d´Electronique de Microelectronique et de Nanotechnologie');
        INSERT INTO institutions (institution) values ('Institut de Biologie Structurale (IBS)');
        INSERT INTO institutions (institution) values ('Institut de Physique et Chemie des Materiaux de Strasbourg (IPCMS)');
        INSERT INTO institutions (institution) values ('Institute for Clinical Sciences Malmö, Lund University');
        INSERT INTO institutions (institution) values ('Institute for Stem Cell Biology and Regenerative Medicine (inStem) ');
        INSERT INTO institutions (institution) values ('Institute for Energy Technology (IFE)');
        INSERT INTO institutions (institution) values ('Institute for Research in Biomedicine (IRB Barcelona)');
        INSERT INTO institutions (institution) values ('Institute of Advanced Chemistry of Catalonia');
        INSERT INTO institutions (institution) values ('Institute of Biochemistry');
        INSERT INTO institutions (institution) values ('Institute of Nuclear Research');
        INSERT INTO institutions (institution) values ('Institute of Organic Chemistry, Polish Academy of Science');
        INSERT INTO institutions (institution) values ('Institute of Physics Belgrade');
        INSERT INTO institutions (institution) values ('Institute of Physics of the Czech Academy of Sciences');
        INSERT INTO institutions (institution) values ('Institute of Bioorganic Chemistry, Polish Academy of Sciences');
        INSERT INTO institutions (institution) values ('Institute of Nuclear Chemistry and Technology');
        INSERT INTO institutions (institution) values ('Institute of Physics, Polish Academy of Science');
        INSERT INTO institutions (institution) values ('Institute of Protein Research RAS');
        INSERT INTO institutions (institution) values ('Instituto Madrileno de Estudios Avanzados IMDEA Nanociencia');
        INSERT INTO institutions (institution) values ('Instituto Superior Tecnico');
        INSERT INTO institutions (institution) values ('Institute of Plasma Physics and Laser Microfusion');
        INSERT INTO institutions (institution) values ('Instituto de Ciencia de Materiales de Aragon - CSIC - Universidad de Zaragoza');
        INSERT INTO institutions (institution) values ('Internationella Engelska Gymnasiet Södermalm (IEGS)');
        INSERT INTO institutions (institution) values ('Irkutsk State University');
        INSERT INTO institutions (institution) values ('Istituto di Metodologie Inorganiche e dei Plasmi - CNR-IMIP');
        INSERT INTO institutions (institution) values ('Ivan Franko National University of Lviv');
        INSERT INTO institutions (institution) values ('Jagiellonian University');
        INSERT INTO institutions (institution) values ('Istituto Italiano di Tecnologia (IIT)');
        INSERT INTO institutions (institution) values ('Istituto Officina dei Materiali IOM-CNR');
        INSERT INTO institutions (institution) values ('Istituto di Struttura della Materia - CNR');
        INSERT INTO institutions (institution) values ('Japan Atomic Energy Research Institute');
        INSERT INTO institutions (institution) values ('Japan Advanced Institute of Science and Technology');
        INSERT INTO institutions (institution) values ('Jerzy Haber Institute of Catalysis and Surface Chemistry, Polish Academy of Sciences');
        INSERT INTO institutions (institution) values ('Johannes Gutenberg-University Mainz');
        INSERT INTO institutions (institution) values ('Japan Synchrotron Radiation Research Institute (JASRI)');
        INSERT INTO institutions (institution) values ('Justus-Liebig-Universität Giessen');
        INSERT INTO institutions (institution) values ('K.U. Leuven');
        INSERT INTO institutions (institution) values ('Karl-Franzens University');
        INSERT INTO institutions (institution) values ('Jozef Stefan Institute');
        INSERT INTO institutions (institution) values ('Karlsruhe Insitute of Technology (KIT)');
        INSERT INTO institutions (institution) values ('Karlstad University');
        INSERT INTO institutions (institution) values ('Karolinska Institutet');
        INSERT INTO institutions (institution) values ('Keio University');
        INSERT INTO institutions (institution) values ('Keuka College');
        INSERT INTO institutions (institution) values ('Kharkov Institute of Physics and Technology');
        INSERT INTO institutions (institution) values ('Kiev National T. Shevchenko University');
        INSERT INTO institutions (institution) values ('King Abdullah University of Science and Technology (KAUST)');
        INSERT INTO institutions (institution) values ('Keele University');
        INSERT INTO institutions (institution) values ('Koç University');
        INSERT INTO institutions (institution) values ('Kumamoto University');
        INSERT INTO institutions (institution) values ('Korea Advanced Institute of Science and Technology (KAIST)');
        INSERT INTO institutions (institution) values ('La Trobe University');
        INSERT INTO institutions (institution) values ('Laboratoire Léon Brillouin');
        INSERT INTO institutions (institution) values ('Laboratoire des Materiaux, Surfaces et Procedes pour la Catalyse (LMSPC-UMR)');
        INSERT INTO institutions (institution) values ('Latvian Biomedical Research and Study Centre');
        INSERT INTO institutions (institution) values ('Latvian Institute of Organic Synthesis');
        INSERT INTO institutions (institution) values ('Laboratori Nazionali di Frascati - INFN');
        INSERT INTO institutions (institution) values ('Lawrence Berkeley National Laboratory, Advanced Light Source (ALS)');
        INSERT INTO institutions (institution) values ('Laboratorio de Estudios Cristalograficos');
        INSERT INTO institutions (institution) values ('Leibnitz Institute for Solid State and Materials Research, IFW');
        INSERT INTO institutions (institution) values ('Laboratoire de Chimie Physique - Matière et rayonnement, CNRS & SU');
        INSERT INTO institutions (institution) values ('Leibniz University Hannover');
        INSERT INTO institutions (institution) values ('Leiden University');
        INSERT INTO institutions (institution) values ('Linköping University');
        INSERT INTO institutions (institution) values ('Linnaeus University');
        INSERT INTO institutions (institution) values ('Leibniz-Institut für innovative Mikroelektronik IHP');
        INSERT INTO institutions (institution) values ('Luleå University of Technology');
        INSERT INTO institutions (institution) values ('Ludwig-Maximilians-Universität München');
        INSERT INTO institutions (institution) values ('Lund University');
        INSERT INTO institutions (institution) values ('Los Alamos National Laboratory');
        INSERT INTO institutions (institution) values ('Macquarie University');
        INSERT INTO institutions (institution) values ('Massey University');
        INSERT INTO institutions (institution) values ('Massachusetts Institute of Technology (MIT)');
        INSERT INTO institutions (institution) values ('Max Delbrück Center for Molecular Medicine in the Helmholtz Association (MDC)');
        INSERT INTO institutions (institution) values ('Max F. Perutz Laboratories (MFPL)');
        INSERT INTO institutions (institution) values ('Max Planck Institut für Kernphysik');
        INSERT INTO institutions (institution) values ('Max Planck Institut für Plasmaphysik');
        INSERT INTO institutions (institution) values ('Malmö University');
        INSERT INTO institutions (institution) values ('Manchester Metropolitan University');
        INSERT INTO institutions (institution) values ('Maria Curie-Sklodowska University');
        INSERT INTO institutions (institution) values ('Martin-Luther-Universität Halle-Wittenberg');
        INSERT INTO institutions (institution) values ('Max Planck Institut für Kohlenforschung');
        INSERT INTO institutions (institution) values ('Max Planck Institute for Chemical Energy Conversion');
        INSERT INTO institutions (institution) values ('Max Planck Institute for Biophysical Chemistry');
        INSERT INTO institutions (institution) values ('Max Planck Institute for Chemical Physics of Solids');
        INSERT INTO institutions (institution) values ('Max Planck Institute for Medical Research');
        INSERT INTO institutions (institution) values ('Max Planck Institute for Metals Research');
        INSERT INTO institutions (institution) values ('Max Planck Institute for Polymer Research');
        INSERT INTO institutions (institution) values ('Max Planck Institute for Solid State Research');
        INSERT INTO institutions (institution) values ('Maynooth University');
        INSERT INTO institutions (institution) values ('Mersin University');
        INSERT INTO institutions (institution) values ('Max Planck Institute of Colloids and Interfaces');
        INSERT INTO institutions (institution) values ('Monash University');
        INSERT INTO institutions (institution) values ('Military University of Technology');
        INSERT INTO institutions (institution) values ('Montgomery College');
        INSERT INTO institutions (institution) values ('Montanuniversität Leoben');
        INSERT INTO institutions (institution) values ('Moscow Institute of Physics and Technology');
        INSERT INTO institutions (institution) values ('Moscow State University');
        INSERT INTO institutions (institution) values ('NORDITA, the Nordic Institute for Theoretical Physics');
        INSERT INTO institutions (institution) values ('Moscow Engineering Physics Institute');
        INSERT INTO institutions (institution) values ('NIMBE - Nanosciences et Innovation pour les Matériaux la Biomédecine et l´Énergie');
        INSERT INTO institutions (institution) values ('Nagoya Institute of Technology');
        INSERT INTO institutions (institution) values ('National Hellenic Research Foundation');
        INSERT INTO institutions (institution) values ('National Food Research Institute');
        INSERT INTO institutions (institution) values ('National Cheng Kung University');
        INSERT INTO institutions (institution) values ('Nencki Institute of Experimental Biology');
        INSERT INTO institutions (institution) values ('National University of Science and Technology (MISIS)');
        INSERT INTO institutions (institution) values ('National Institute for Medical Research');
        INSERT INTO institutions (institution) values ('Newcastle University');
        INSERT INTO institutions (institution) values ('Nikolaev Institute of Inorganic Chemistry');
        INSERT INTO institutions (institution) values ('Norwegian University of Life Sciences (NMBU)');
        INSERT INTO institutions (institution) values ('Northwestern University');
        INSERT INTO institutions (institution) values ('New Mexico State University');
        INSERT INTO institutions (institution) values ('Norwegian University of Science and Technology (NTNU)');
        INSERT INTO institutions (institution) values ('Oregon State University');
        INSERT INTO institutions (institution) values ('Okinawa Institute of Science and Technology Graduate University (OIST)');
        INSERT INTO institutions (institution) values ('Osaka University');
        INSERT INTO institutions (institution) values ('P.N. Lebedev Physical Institute');
        INSERT INTO institutions (institution) values ('Paul Scherrer Institute (PSI)');
        INSERT INTO institutions (institution) values ('Oak Ridge National Laboratory');
        INSERT INTO institutions (institution) values ('Pavol Josef Šafárik University in Košice');
        INSERT INTO institutions (institution) values ('Penn State University');
        INSERT INTO institutions (institution) values ('Philipps-University Marburg');
        INSERT INTO institutions (institution) values ('Peter the Great St. Petersburg Polytechnic University');
        INSERT INTO institutions (institution) values ('Peking University');
        INSERT INTO institutions (institution) values ('Pohang University of Science and Technology');
        INSERT INTO institutions (institution) values ('Polytechnic University of Marche');
        INSERT INTO institutions (institution) values ('Princeton University');
        INSERT INTO institutions (institution) values ('Purdue University');
        INSERT INTO institutions (institution) values ('RISE Research Institute of Sweden');
        INSERT INTO institutions (institution) values ('RMIT University');
        INSERT INTO institutions (institution) values ('Rice University');
        INSERT INTO institutions (institution) values ('Quanzhou Normal University');
        INSERT INTO institutions (institution) values ('Queen Mary University of London');
        INSERT INTO institutions (institution) values ('Risø National Laboratory for Sustainable Energy- DTU');
        INSERT INTO institutions (institution) values ('Royal Institute of Technology (KTH)');
        INSERT INTO institutions (institution) values ('Riga Technical University');
        INSERT INTO institutions (institution) values ('Rudjer Boskovic Institute');
        INSERT INTO institutions (institution) values ('Ruhr-University Bochum');
        INSERT INTO institutions (institution) values ('Rutherford Appleton Laboratory - Central Laser Facility');
        INSERT INTO institutions (institution) values ('ISIS Neutron and Muon Facility');
        INSERT INTO institutions (institution) values ('Rzhanov Institute of Semiconductor Physics');
        INSERT INTO institutions (institution) values ('SCK-CEN, Belgian Nuclear Research Centre');
        INSERT INTO institutions (institution) values ('Russian Research Centre');
        INSERT INTO institutions (institution) values ('SESAME Synchrotron');
        INSERT INTO institutions (institution) values ('SIK, the Swedish Institute for Food and Biotechnology');
        INSERT INTO institutions (institution) values ('SINTEF Materials and Chemistry');
        INSERT INTO institutions (institution) values ('SLAC National Accelerator Laboratory');
        INSERT INTO institutions (institution) values ('SOLEIL Synchrotron');
        INSERT INTO institutions (institution) values ('SP Technical Research Institute of Sweden');
        INSERT INTO institutions (institution) values ('SPCTS - Science of Ceramic Processing and Surface Treatment');
        INSERT INTO institutions (institution) values ('Saha Institute of Nuclear Physics');
        INSERT INTO institutions (institution) values ('Sahlgrenska Academy at the University of Gothenburg');
        INSERT INTO institutions (institution) values ('Shanghai Jiao Tong University');
        INSERT INTO institutions (institution) values ('Shanghai Institute of Applied Physics, Chinese Academy of Sciences');
        INSERT INTO institutions (institution) values ('Shaanxi Normal University');
        INSERT INTO institutions (institution) values ('ShanghaiTech Uiversity');
        INSERT INTO institutions (institution) values ('Shenyang Agricultural University');
        INSERT INTO institutions (institution) values ('Slovak Academy of Sciences');
        INSERT INTO institutions (institution) values ('South China University of Technology');
        INSERT INTO institutions (institution) values ('Southeast University');
        INSERT INTO institutions (institution) values ('South Westphalia University of Applied Sciences');
        INSERT INTO institutions (institution) values ('Southern Federal University');
        INSERT INTO institutions (institution) values ('Southern University of Science and Technology (SUSTech)');
        INSERT INTO institutions (institution) values ('Stockholm University');
        INSERT INTO institutions (institution) values ('Statens Serum Institut');
        INSERT INTO institutions (institution) values ('Stony Brook University');
        INSERT INTO institutions (institution) values ('Sveriges Geologiska Undersökning (SGU)');
        INSERT INTO institutions (institution) values ('Swedish Defence Research Agency (FOI)');
        INSERT INTO institutions (institution) values ('Swedish Geotechnical Institute (SGI)');
        INSERT INTO institutions (institution) values ('Swedish Museum of Natural History');
        INSERT INTO institutions (institution) values ('Swedish Army Research Agency');
        INSERT INTO institutions (institution) values ('Swedish University of Agricultural Sciences (SLU), Alnarp');
        INSERT INTO institutions (institution) values ('Swedish Orphan Biovitrum');
        INSERT INTO institutions (institution) values ('Swedish University of Agricultural Sciences (SLU), Umeå');
        INSERT INTO institutions (institution) values ('Swedish University of Agricultural Sciences (SLU), Uppsala');
        INSERT INTO institutions (institution) values ('Tampere University');
        INSERT INTO institutions (institution) values ('Tarbiat Modares University');
        INSERT INTO institutions (institution) values ('TU Bergakademie Freiberg');
        INSERT INTO institutions (institution) values ('Szczecin Technical University');
        INSERT INTO institutions (institution) values ('Technical University of Denmark (DTU)');
        INSERT INTO institutions (institution) values ('Technical University of Kaiserslautern');
        INSERT INTO institutions (institution) values ('Technical University of Košice');
        INSERT INTO institutions (institution) values ('Technical University of Lodz');
        INSERT INTO institutions (institution) values ('Technische Universität Dresden');
        INSERT INTO institutions (institution) values ('Technion - Israel Institute of Technology');
        INSERT INTO institutions (institution) values ('Technische Universität Berlin');
        INSERT INTO institutions (institution) values ('Technische Universität Chemnitz');
        INSERT INTO institutions (institution) values ('Technische Universität München');
        INSERT INTO institutions (institution) values ('Tel Aviv University');
        INSERT INTO institutions (institution) values ('Tele and Radio Research Institute');
        INSERT INTO institutions (institution) values ('Tetra Pak');
        INSERT INTO institutions (institution) values ('The Andrzej Soltan Institute for Nuclear Studies');
        INSERT INTO institutions (institution) values ('The Hebrew University');
        INSERT INTO institutions (institution) values ('The Hashemite University');
        INSERT INTO institutions (institution) values ('Technische Universität Wien');
        INSERT INTO institutions (institution) values ('The University of Tokyo');
        INSERT INTO institutions (institution) values ('The Open University');
        INSERT INTO institutions (institution) values ('The University of New South Wales');
        INSERT INTO institutions (institution) values ('The University of Tokyo, Outstation SPring-8');
        INSERT INTO institutions (institution) values ('Tomsk Polytechnic University ');
        INSERT INTO institutions (institution) values ('The Novo Nordisk Foundation Center for Protein Research');
        INSERT INTO institutions (institution) values ('Trinity College Dublin');
        INSERT INTO institutions (institution) values ('UNICAMP, University of Campinas');
        INSERT INTO institutions (institution) values ('UMONS University of Mons');
        INSERT INTO institutions (institution) values ('Umeå University');
        INSERT INTO institutions (institution) values ('UCIBIO - Applied Molecular Biosciences Unit');
        INSERT INTO institutions (institution) values ('Universidad Autonoma de Madrid');
        INSERT INTO institutions (institution) values ('Universidad Nacional Autonoma de Mexico (UNAM)');
        INSERT INTO institutions (institution) values ('Universidad Complutense de Madrid');
        INSERT INTO institutions (institution) values ('Universidad Politecnica de Madrid');
        INSERT INTO institutions (institution) values ('Universidad de Valencia');
        INSERT INTO institutions (institution) values ('Universidade Federal da Bahia');
        INSERT INTO institutions (institution) values ('Universidade de Sao Paulo');
        INSERT INTO institutions (institution) values ('Universita degli Studi di Milano');
        INSERT INTO institutions (institution) values ('Universita degli Studi di Palermo');
        INSERT INTO institutions (institution) values ('Universita degli Studi di Torino');
        INSERT INTO institutions (institution) values ('Universita degli Studi Roma TRE');
        INSERT INTO institutions (institution) values ('Universite Claude Bernard Lyon 1');
        INSERT INTO institutions (institution) values ('Universite Montpellier II');
        INSERT INTO institutions (institution) values ('Universite Paris 13');
        INSERT INTO institutions (institution) values ('Universite Paris Sud');
        INSERT INTO institutions (institution) values ('Universitat Autonoma de Barcelona');
        INSERT INTO institutions (institution) values ('Universite Paris Sud 11');
        INSERT INTO institutions (institution) values ('Universite Pierre et Marie Curie - Paris VI');
        INSERT INTO institutions (institution) values ('Universite d Orleans');
        INSERT INTO institutions (institution) values ('Universite de Cergy-Pontoise');
        INSERT INTO institutions (institution) values ('Universite de Strasbourg');
        INSERT INTO institutions (institution) values ('Universite Paris-Sud');
        INSERT INTO institutions (institution) values ('University College Dublin');
        INSERT INTO institutions (institution) values ('University Medical Centre Göttingen');
        INSERT INTO institutions (institution) values ('University of Alicante');
        INSERT INTO institutions (institution) values ('University of Antwerp');
        INSERT INTO institutions (institution) values ('University of Amsterdam');
        INSERT INTO institutions (institution) values ('University College London');
        INSERT INTO institutions (institution) values ('University of Babes-Bolyai');
        INSERT INTO institutions (institution) values ('University of Barcelona');
        INSERT INTO institutions (institution) values ('University of Bayreuth');
        INSERT INTO institutions (institution) values ('University of Bergen');
        INSERT INTO institutions (institution) values ('University of Athens');
        INSERT INTO institutions (institution) values ('University of Basel');
        INSERT INTO institutions (institution) values ('University of Bath');
        INSERT INTO institutions (institution) values ('University of Bialystok');
        INSERT INTO institutions (institution) values ('University of Bologna');
        INSERT INTO institutions (institution) values ('University of Bordeaux');
        INSERT INTO institutions (institution) values ('University of Bradford');
        INSERT INTO institutions (institution) values ('University of Brasilia');
        INSERT INTO institutions (institution) values ('University of Bremen');
        INSERT INTO institutions (institution) values ('University of Brighton');
        INSERT INTO institutions (institution) values ('University of Bristol');
        INSERT INTO institutions (institution) values ('University of California, Los Angeles');
        INSERT INTO institutions (institution) values ('University of California, Santa Barbara');
        INSERT INTO institutions (institution) values ('University of Cambridge');
        INSERT INTO institutions (institution) values ('University of Bordeaux');
        INSERT INTO institutions (institution) values ('University of Cape Town');
        INSERT INTO institutions (institution) values ('University of Coimbra');
        INSERT INTO institutions (institution) values ('University of Colorado');
        INSERT INTO institutions (institution) values ('University of Connecticut');
        INSERT INTO institutions (institution) values ('University of Copenhagen');
        INSERT INTO institutions (institution) values ('University of Central Florida');
        INSERT INTO institutions (institution) values ('University of Central Lancashire');
        INSERT INTO institutions (institution) values ('University of Cordoba');
        INSERT INTO institutions (institution) values ('University of Eastern Finland');
        INSERT INTO institutions (institution) values ('University of Dundee');
        INSERT INTO institutions (institution) values ('University of East Anglia');
        INSERT INTO institutions (institution) values ('University of Edinburgh');
        INSERT INTO institutions (institution) values ('University of Freiburg');
        INSERT INTO institutions (institution) values ('University of Fribourg');
        INSERT INTO institutions (institution) values ('University of Gdansk');
        INSERT INTO institutions (institution) values ('University of Geneva');
        INSERT INTO institutions (institution) values ('University of Glasgow');
        INSERT INTO institutions (institution) values ('University of Florida');
        INSERT INTO institutions (institution) values ('University of Gothenburg');
        INSERT INTO institutions (institution) values ('University of Helsinki');
        INSERT INTO institutions (institution) values ('University of Greifswald');
        INSERT INTO institutions (institution) values ('University of Groningen');
        INSERT INTO institutions (institution) values ('University of Iceland');
        INSERT INTO institutions (institution) values ('University of Illinois');
        INSERT INTO institutions (institution) values ('University of Innsbruck');
        INSERT INTO institutions (institution) values ('University of Ioannina');
        INSERT INTO institutions (institution) values ('University of Hyogo');
        INSERT INTO institutions (institution) values ('University of Jordan');
        INSERT INTO institutions (institution) values ('University of Jyväskylä');
        INSERT INTO institutions (institution) values ('University of Kassel');
        INSERT INTO institutions (institution) values ('University of Kentucky');
        INSERT INTO institutions (institution) values ('University of L´Aquila');
        INSERT INTO institutions (institution) values ('University of Latvia');
        INSERT INTO institutions (institution) values ('University of Leeds');
        INSERT INTO institutions (institution) values ('University of Leicester');
        INSERT INTO institutions (institution) values ('University of Limerick');
        INSERT INTO institutions (institution) values ('University of Manchester');
        INSERT INTO institutions (institution) values ('University of Massachusetts Dartmouth');
        INSERT INTO institutions (institution) values ('University of Ljubljana');
        INSERT INTO institutions (institution) values ('University of Lübeck');
        INSERT INTO institutions (institution) values ('University of Melbourne');
        INSERT INTO institutions (institution) values ('University of Minho');
        INSERT INTO institutions (institution) values ('University of Michigan');
        INSERT INTO institutions (institution) values ('University of Nis');
        INSERT INTO institutions (institution) values ('University of Natural Resources and Applied Life Sciences');
        INSERT INTO institutions (institution) values ('University of Nottingham');
        INSERT INTO institutions (institution) values ('University of Oslo');
        INSERT INTO institutions (institution) values ('University of Oulu');
        INSERT INTO institutions (institution) values ('University of Oradea');
        INSERT INTO institutions (institution) values ('University of Nova Gorica');
        INSERT INTO institutions (institution) values ('University of Oslo - Oslo University Hospital');
        INSERT INTO institutions (institution) values ('University of Oxford');
        INSERT INTO institutions (institution) values ('University of Oviedo');
        INSERT INTO institutions (institution) values ('University of Patras');
        INSERT INTO institutions (institution) values ('University of Padova');
        INSERT INTO institutions (institution) values ('University of Poitiers');
        INSERT INTO institutions (institution) values ('University of Potsdam');
        INSERT INTO institutions (institution) values ('University of Reading');
        INSERT INTO institutions (institution) values ('University of Regensburg');
        INSERT INTO institutions (institution) values ('University of Portsmouth');
        INSERT INTO institutions (institution) values ('University of Porto');
        INSERT INTO institutions (institution) values ('University of Pretoria');
        INSERT INTO institutions (institution) values ('University of Rome La Sapienza');
        INSERT INTO institutions (institution) values ('University of Rome Tor Vergata');
        INSERT INTO institutions (institution) values ('University of Sao Paulo');
        INSERT INTO institutions (institution) values ('University of Roskilde');
        INSERT INTO institutions (institution) values ('University of Saarland');
        INSERT INTO institutions (institution) values ('University of Santiago de Compostela');
        INSERT INTO institutions (institution) values ('University of Sassari');
        INSERT INTO institutions (institution) values ('University of Saskatchewan');
        INSERT INTO institutions (institution) values ('University of Sherbrooke');
        INSERT INTO institutions (institution) values ('University of Silesia');
        INSERT INTO institutions (institution) values ('University of Science and Technology of China');
        INSERT INTO institutions (institution) values ('University of Skövde');
        INSERT INTO institutions (institution) values ('University of Science and Technology Beijing');
        INSERT INTO institutions (institution) values ('University of Siegen');
        INSERT INTO institutions (institution) values ('University of Southampton');
        INSERT INTO institutions (institution) values ('University of Southern Denmark');
        INSERT INTO institutions (institution) values ('University of St Andrews');
        INSERT INTO institutions (institution) values ('University of St. Petersburg');
        INSERT INTO institutions (institution) values ('University of Stavanger');
        INSERT INTO institutions (institution) values ('University of Thessaly');
        INSERT INTO institutions (institution) values ('University of Tartu');
        INSERT INTO institutions (institution) values ('University of Toronto');
        INSERT INTO institutions (institution) values ('University of Szeged');
        INSERT INTO institutions (institution) values ('University of Tromsø');
        INSERT INTO institutions (institution) values ('University of Turku');
        INSERT INTO institutions (institution) values ('University of Trento');
        INSERT INTO institutions (institution) values ('University of Ulster');
        INSERT INTO institutions (institution) values ('University of Ulster, Jordanstown campus');
        INSERT INTO institutions (institution) values ('University of Verona');
        INSERT INTO institutions (institution) values ('University of Vienna');
        INSERT INTO institutions (institution) values ('University of Twente');
        INSERT INTO institutions (institution) values ('University of Virginia');
        INSERT INTO institutions (institution) values ('University of Wisconsin-Madison');
        INSERT INTO institutions (institution) values ('University of Wisconsin-Milwaukee');
        INSERT INTO institutions (institution) values ('University of Warsaw');
        INSERT INTO institutions (institution) values ('University of Warwick');
        INSERT INTO institutions (institution) values ('University of Wollongong');
        INSERT INTO institutions (institution) values ('University of the Basque Country');
        INSERT INTO institutions (institution) values ('University of Zürich');
        INSERT INTO institutions (institution) values ('Università degli Studi di Genova');
        INSERT INTO institutions (institution) values ('University of the Sunshine Coast');
        INSERT INTO institutions (institution) values ('University of York');
        INSERT INTO institutions (institution) values ('Universität Augsburg');
        INSERT INTO institutions (institution) values ('Universität Göttingen');
        INSERT INTO institutions (institution) values ('Universität Hamburg');
        INSERT INTO institutions (institution) values ('Universität Heidelberg');
        INSERT INTO institutions (institution) values ('Università degli Studi di Trieste');
        INSERT INTO institutions (institution) values ('Universität Kiel');
        INSERT INTO institutions (institution) values ('Universität Würzburg');
        INSERT INTO institutions (institution) values ('Universität Osnabrück');
        INSERT INTO institutions (institution) values ('Universität Leipzig');
        INSERT INTO institutions (institution) values ('Universität zu Köln');
        INSERT INTO institutions (institution) values ('Universität Konstanz');
        INSERT INTO institutions (institution) values ('Université de Montpellier');
        INSERT INTO institutions (institution) values ('Uppsala University');
        INSERT INTO institutions (institution) values ('Université Grenoble Alpes');
        INSERT INTO institutions (institution) values ('Ural Division of the Russian Academy of Sciences');
        INSERT INTO institutions (institution) values ('Urmia University');
        INSERT INTO institutions (institution) values ('Utrecht University');
        INSERT INTO institutions (institution) values ('Ural Federal University');
        INSERT INTO institutions (institution) values ('Ural State Technical University');
        INSERT INTO institutions (institution) values ('VSB-Technical University of Ostrava');
        INSERT INTO institutions (institution) values ('Vienna University of Technology');
        INSERT INTO institutions (institution) values ('Vilnius University');
        INSERT INTO institutions (institution) values ('Victoria University of Wellington');
        INSERT INTO institutions (institution) values ('Voronezh State University');
        INSERT INTO institutions (institution) values ('Vrije Universiteit Brussel');
        INSERT INTO institutions (institution) values ('W. Trzebiatowski Institute of Low Temperature and Structure Research, Polish Academy of Sciences');
        INSERT INTO institutions (institution) values ('Weill Cornell Medical College, Cornell University');
        INSERT INTO institutions (institution) values ('Weizmann Institute of Science');
        INSERT INTO institutions (institution) values ('Vinogradov Institute of Geochemistry SB RAS');
        INSERT INTO institutions (institution) values ('Wageningen University');
        INSERT INTO institutions (institution) values ('Wigner Research Centre for Physics');
        INSERT INTO institutions (institution) values ('Wuhan University');
        INSERT INTO institutions (institution) values ('Yonsei University');
        INSERT INTO institutions (institution) values ('YKI, Institute for Surface Chemistry');
        INSERT INTO institutions (institution) values ('Yeditepe University');
        INSERT INTO institutions (institution) values ('ZHAW - Zürcher Hochschule für Angewandte Wissenschaften');
        INSERT INTO institutions (institution) values ('Zhejiang University');
        INSERT INTO institutions (institution) values ('Wroclaw University of Technology');
        INSERT INTO institutions (institution) values ('Wihuri Research Institute');
        INSERT INTO institutions (institution) values ('Örebro University');
        INSERT INTO institutions (institution) values ('Åbo Akademi University');



    END;
	END IF;
END;
$$
LANGUAGE plpgsql;
