DO
$DO$
BEGIN
  IF register_patch('CreateUpdateUserIdFunc.sql', 'Chi Kai Lam', 'Update user id for merging', '2024-02-15') THEN
    BEGIN
      
      CREATE OR REPLACE FUNCTION UPDATE_USER_ID(INOUT P_OLD_USER_ID BIGINT, INOUT P_NEW_USER_ID BIGINT)
      LANGUAGE PLPGSQL AS
      $$
      DECLARE
        NEW_USER_CNT     INTEGER := 0;
        OLD_USER_CNT     INTEGER := 0;
      BEGIN
          IF P_OLD_USER_ID = P_NEW_USER_ID THEN 
              RETURN;
          END IF; 
          SELECT COUNT(*) FROM USERS WHERE USER_ID = P_OLD_USER_ID INTO OLD_USER_CNT;
          IF OLD_USER_CNT = 0 THEN 
              RETURN;
          END IF; 
          SELECT COUNT(*) FROM USERS WHERE USER_ID = P_NEW_USER_ID INTO NEW_USER_CNT;
          IF NEW_USER_CNT = 0 THEN
              INSERT INTO USERS (USER_ID, FIRSTNAME, LASTNAME, USERNAME, GENDER, BIRTHDATE, DEPARTMENT, POSITION, EMAIL, TELEPHONE) 
                VALUES (P_NEW_USER_ID, '', '', P_NEW_USER_ID, '', now(), '', '', P_NEW_USER_ID, '');
          END IF;
          --Update TABLES row with OLD USER ID to NEW USER ID
          UPDATE EVENT_LOGS SET CHANGED_BY = P_NEW_USER_ID WHERE CHANGED_BY = P_OLD_USER_ID; 
          UPDATE EXPERIMENT_SAFETY_INPUTS SET CREATOR_ID = P_NEW_USER_ID WHERE CREATOR_ID = P_OLD_USER_ID; 
          UPDATE FAP_MEETING_DECISIONS SET SUBMITTED_BY = P_NEW_USER_ID WHERE SUBMITTED_BY = P_OLD_USER_ID; 
          UPDATE FAPS SET FAP_CHAIR_USER_ID = P_NEW_USER_ID WHERE FAP_CHAIR_USER_ID = P_OLD_USER_ID; 
          UPDATE FEEDBACKS SET CREATOR_ID = P_NEW_USER_ID WHERE CREATOR_ID = P_OLD_USER_ID; 
          UPDATE GENERIC_TEMPLATES SET CREATOR_ID = P_NEW_USER_ID WHERE CREATOR_ID = P_OLD_USER_ID; 
          UPDATE INSTRUMENTS SET MANAGER_USER_ID = P_NEW_USER_ID WHERE MANAGER_USER_ID = P_OLD_USER_ID; 
          UPDATE INTERNAL_REVIEWS SET ASSIGNED_BY = P_NEW_USER_ID WHERE ASSIGNED_BY = P_OLD_USER_ID; 
          UPDATE INTERNAL_REVIEWS SET REVIEWER_ID = P_NEW_USER_ID WHERE REVIEWER_ID = P_OLD_USER_ID; 
          UPDATE PDF_TEMPLATES SET CREATOR_ID = P_NEW_USER_ID WHERE CREATOR_ID = P_OLD_USER_ID; 
          UPDATE PREDEFINED_MESSAGES SET LAST_MODIFIED_BY = P_NEW_USER_ID WHERE LAST_MODIFIED_BY = P_OLD_USER_ID; 
          UPDATE PROPOSALS SET PROPOSER_ID = P_NEW_USER_ID WHERE PROPOSER_ID = P_OLD_USER_ID; 
          UPDATE QUESTIONARIES SET CREATOR_ID = P_NEW_USER_ID WHERE CREATOR_ID = P_OLD_USER_ID; 
          UPDATE REDEEM_CODES SET CLAIMED_BY = P_NEW_USER_ID WHERE CLAIMED_BY = P_OLD_USER_ID; 
          UPDATE REDEEM_CODES SET CREATED_BY = P_NEW_USER_ID WHERE CREATED_BY = P_OLD_USER_ID; 
          UPDATE REDEEM_CODES SET PLACEHOLDER_USER_ID = P_NEW_USER_ID WHERE PLACEHOLDER_USER_ID = P_OLD_USER_ID; 
          UPDATE SAMPLES SET CREATOR_ID = P_NEW_USER_ID WHERE CREATOR_ID = P_OLD_USER_ID; 
          UPDATE SCHEDULED_EVENTS SET LOCAL_CONTACT = P_NEW_USER_ID WHERE LOCAL_CONTACT = P_OLD_USER_ID; 
          UPDATE SHIPMENTS SET CREATOR_ID = P_NEW_USER_ID WHERE CREATOR_ID = P_OLD_USER_ID; 
          UPDATE TECHNICAL_REVIEW SET REVIEWER_ID = P_NEW_USER_ID WHERE REVIEWER_ID = P_OLD_USER_ID; 
          UPDATE TECHNICAL_REVIEW SET technical_review_assignee_id = P_NEW_USER_ID WHERE technical_review_assignee_id = P_OLD_USER_ID; 
          UPDATE VISITS SET CREATOR_ID = P_NEW_USER_ID WHERE CREATOR_ID = P_OLD_USER_ID; 
          UPDATE VISITS SET TEAM_LEAD_USER_ID = P_NEW_USER_ID WHERE TEAM_LEAD_USER_ID = P_OLD_USER_ID; 

          --Update TABLES row with OLD USER ID that is not overlap with NEW USER ID and then
          --Delete TABLES row with OLD USER ID that is overlap with NEW USER ID  
          UPDATE FAP_REVIEWERS SET USER_ID = P_NEW_USER_ID WHERE USER_ID = P_OLD_USER_ID 
            AND FAP_ID NOT IN ( SELECT FAP_ID FROM  FAP_REVIEWERS WHERE USER_ID = P_NEW_USER_ID );
          DELETE FROM FAP_REVIEWERS WHERE USER_ID = P_OLD_USER_ID;

          UPDATE FAP_REVIEWS SET USER_ID = P_NEW_USER_ID WHERE USER_ID = P_OLD_USER_ID 
            AND PROPOSAL_PK NOT IN ( SELECT PROPOSAL_PK FROM  FAP_REVIEWS WHERE USER_ID = P_NEW_USER_ID );
          DELETE FROM FAP_REVIEWS WHERE USER_ID = P_OLD_USER_ID;

          UPDATE INSTRUMENT_HAS_SCIENTISTS SET USER_ID = P_NEW_USER_ID WHERE USER_ID = P_OLD_USER_ID 
            AND INSTRUMENT_ID NOT IN ( SELECT INSTRUMENT_ID FROM INSTRUMENT_HAS_SCIENTISTS WHERE USER_ID = P_NEW_USER_ID ) ;
          DELETE FROM INSTRUMENT_HAS_SCIENTISTS WHERE USER_ID = P_OLD_USER_ID;

          UPDATE PROPOSAL_USER SET USER_ID = P_NEW_USER_ID WHERE USER_ID = P_OLD_USER_ID 
            AND PROPOSAL_PK NOT IN ( SELECT PROPOSAL_PK FROM PROPOSAL_USER WHERE USER_ID = P_NEW_USER_ID );
          DELETE FROM PROPOSAL_USER WHERE USER_ID = P_OLD_USER_ID;

          UPDATE ROLE_USER SET USER_ID = P_NEW_USER_ID WHERE USER_ID = P_OLD_USER_ID 
            AND ROLE_ID NOT IN ( SELECT ROLE_ID FROM ROLE_USER WHERE USER_ID = P_NEW_USER_ID );
          DELETE FROM ROLE_USER WHERE USER_ID = P_OLD_USER_ID;

          UPDATE VISITS_HAS_USERS SET USER_ID = P_NEW_USER_ID WHERE USER_ID = P_OLD_USER_ID 
            AND VISIT_ID NOT IN ( SELECT VISIT_ID FROM VISITS_HAS_USERS WHERE USER_ID = P_NEW_USER_ID );
          DELETE FROM VISITS_HAS_USERS WHERE USER_ID = P_OLD_USER_ID;

          UPDATE FAP_SECRETARIES SET USER_ID = P_NEW_USER_ID WHERE USER_ID = P_OLD_USER_ID 
            AND FAP_ID NOT IN ( SELECT FAP_ID FROM FAP_SECRETARIES WHERE USER_ID = P_NEW_USER_ID ) ;
          DELETE FROM FAP_SECRETARIES WHERE USER_ID = P_OLD_USER_ID;

          UPDATE FAP_ASSIGNMENTS SET FAP_MEMBER_USER_ID = P_NEW_USER_ID WHERE FAP_MEMBER_USER_ID = P_OLD_USER_ID AND 
          (PROPOSAL_PK, FAP_ID) NOT IN ( SELECT PROPOSAL_PK, FAP_ID FROM FAP_ASSIGNMENTS WHERE fap_member_user_id = P_NEW_USER_ID );

          DELETE FROM FAP_ASSIGNMENTS WHERE FAP_MEMBER_USER_ID = P_OLD_USER_ID AND 
          (PROPOSAL_PK, FAP_ID) IN ( SELECT PROPOSAL_PK, FAP_ID FROM FAP_ASSIGNMENTS WHERE fap_member_user_id = P_NEW_USER_ID );

          DELETE FROM USERS WHERE USER_ID = P_OLD_USER_ID;

          RETURN; 
          COMMIT;
          EXCEPTION WHEN OTHERS THEN
              ROLLBACK;
              RAISE EXCEPTION 'ROLLBACK UPDATE_USER_ID FUNC WITH OLD USER ID: % AND NEW USER ID: %', P_OLD_USER_ID, P_NEW_USER_ID;
      END;
      $$;
    END;
  END IF;
END;
$DO$;
