name: Deploy Documentation for Develop version
# When a push event occurs on the develop branch, and the changes are in the documentation folder, the workflow is triggered
on:
  push:
    branches:
      - develop
    paths:
      - 'documentation/**'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: pip install mike
      - name: Build and Deploy
        working-directory: ./documentation
        run: |
          git fetch origin
          mike deploy --update-alias --push develop