name: CI
 
on: [push]
 
jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v6

      - name: Set up postgress dbs
        run: |
          docker compose -f docker-compose-graphql-inspection.yml up -d db-base db-new

          sleep 10 

          docker ps

      - name: bring up container for schema
        run: |
          docker compose -f docker-compose-graphql-inspection.yml up -d 

          sleep 20 

          docker ps
            
      # This doesn't work see https://github.com/graphql-hive/graphql-inspector/issues/2876
      # - uses: graphql-hive/graphql-inspector@master
      #   with:
      #     schema: 'http://localhost:4000/graphql'
      #     endpoint: 'http://localhost:4001/graphql'

      
      - name: manual graphql schema check
        run: |
          npm i --global @graphql-inspector/cli graphql
          graphql-inspector diff http://localhost:4001/graphql http://localhost:4001/graphql


      - name: check logs of containers on failure
        if: failure()
        run: |
          echo "Checking logs of containers on failure"
          docker compose -f docker-compose-graphql-inspection.yml logs backend-base
          docker compose -f docker-compose-graphql-inspection.yml logs backend-new


      - name: bring down containers
        run: |
          docker compose -f docker-compose-graphql-inspection.yml down